//! Build script: compile the gRPC schema with `tonic-build`, using the pinned
//! **vendored** `protoc` so neither CI nor local dev needs a system protobuf
//! compiler (ships linux-x86_64 + macos-aarch64). Generation is
//! deterministic — pinned protoc + fixed `.proto` produce byte-identical Rust
//! across the two clean release builds of the byte-determinism gate (I1.c).
//!
//! ## The descriptor set, and why it does not endanger that gate
//!
//! We additionally ask `tonic-build` for a `FileDescriptorSet` and generate
//! `control_index.rs` from it — the machine-known half of the `ControlSurface`
//! (`kx_gateway_core::control_surface`): every `KxGateway` RPC, its request and
//! response type, and whether it streams. The judgement half (domain, read vs
//! mutate, required authority) is hand-authored there, because a descriptor
//! cannot know it.
//!
//! Three properties keep I1.c true:
//!
//! 1. **No absolute path reaches the descriptor.** `compile_protos` is handed a
//!    relative include (`proto`) and relative file paths, so every
//!    `FileDescriptorProto.name` is repo-relative (`kortecx/v1/gateway.proto`).
//! 2. **No external import.** The two protos import only each other, so
//!    `--include_imports` pulls in nothing outside this repo — no well-known type
//!    from whatever protoc happens to ship.
//! 3. **The descriptor bytes never reach a shipped rlib.** Rust *source* is
//!    generated from it here; the `.fds` itself is read only by this script and,
//!    under `cfg(test)`, by the guard that cross-checks the generated index
//!    against an independent read of the `.proto` text.
//!
//! `skip_source_info()` is deliberately NOT set: it would also strip the doc
//! comments prost emits onto every generated message — a large, unrelated diff in
//! the generated Rust for no benefit here.

use std::io::Write;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Point tonic-build / prost-build at the vendored protoc binary instead of
    // requiring one on PATH. `set_var` is safe on edition 2021.
    let protoc = protoc_bin_vendored::protoc_bin_path()?;
    std::env::set_var("PROTOC", protoc);

    let out_dir = std::path::PathBuf::from(std::env::var("OUT_DIR")?);
    let fds_path = out_dir.join("kortecx.fds");

    tonic_build::configure()
        .build_server(true)
        .build_client(true)
        .file_descriptor_set_path(&fds_path)
        .compile_protos(
            &[
                "proto/kortecx/v1/coordinator.proto",
                "proto/kortecx/v1/gateway.proto",
            ],
            &["proto"],
        )?;

    generate_control_index(&fds_path, &out_dir.join("control_index.rs"))?;

    println!("cargo:rerun-if-changed=proto/kortecx/v1/coordinator.proto");
    println!("cargo:rerun-if-changed=proto/kortecx/v1/gateway.proto");
    Ok(())
}

/// One RPC, exactly as the descriptor knows it.
struct Rpc {
    name: String,
    request: String,
    response: String,
    server_streaming: bool,
}

/// Emit `enum GatewayRpc` + its accessors from the compiled descriptor set.
///
/// The enum is deliberately NOT `#[non_exhaustive]`: an exhaustive `match` over it
/// downstream is what turns "a new RPC nobody classified" into a COMPILE error
/// (`E0004`) instead of a capability that is quietly unreachable. Marking it
/// non-exhaustive would force wildcard arms everywhere and destroy that property.
///
/// Iteration order is descriptor declaration order — deterministic, and it groups
/// the domains the way the `.proto` already does.
fn generate_control_index(
    fds_path: &std::path::Path,
    out: &std::path::Path,
) -> Result<(), Box<dyn std::error::Error>> {
    use prost::Message as _;

    let bytes = std::fs::read(fds_path)?;
    let set = prost_types::FileDescriptorSet::decode(&bytes[..])?;

    let mut rpcs: Vec<Rpc> = Vec::new();
    for file in &set.file {
        for service in &file.service {
            if service.name() != "KxGateway" {
                continue;
            }
            for m in &service.method {
                rpcs.push(Rpc {
                    name: m.name().to_string(),
                    request: strip_leading_dot(m.input_type()),
                    response: strip_leading_dot(m.output_type()),
                    server_streaming: m.server_streaming(),
                });
            }
        }
    }

    if rpcs.is_empty() {
        return Err("no KxGateway service found in the descriptor set".into());
    }

    let mut f = std::io::BufWriter::new(std::fs::File::create(out)?);

    writeln!(
        f,
        "// @generated by kx-proto/build.rs from the compiled FileDescriptorSet."
    )?;
    writeln!(f, "// EDIT THE .proto, NOT THIS FILE.")?;
    writeln!(f)?;
    writeln!(
        f,
        "/// Every RPC on the `KxGateway` service, as the wire declares it."
    )?;
    writeln!(f, "///")?;
    writeln!(
        f,
        "/// NOT `#[non_exhaustive]`, on purpose: an exhaustive `match` over this enum is"
    )?;
    writeln!(
        f,
        "/// what turns \"a new RPC nobody classified\" into a compile error rather than a"
    )?;
    writeln!(
        f,
        "/// capability that is quietly unreachable. See `kx_gateway_core::control_surface`."
    )?;
    writeln!(
        f,
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]"
    )?;
    writeln!(f, "pub enum GatewayRpc {{")?;
    for r in &rpcs {
        writeln!(
            f,
            "    /// `{}` — `{}` -> `{}`.",
            r.name, r.request, r.response
        )?;
        writeln!(f, "    {},", r.name)?;
    }
    writeln!(f, "}}")?;
    writeln!(f)?;

    writeln!(f, "impl GatewayRpc {{")?;
    writeln!(f, "    /// Every RPC, in `.proto` declaration order.")?;
    writeln!(f, "    pub const ALL: &'static [GatewayRpc] = &[")?;
    for r in &rpcs {
        writeln!(f, "        GatewayRpc::{},", r.name)?;
    }
    writeln!(f, "    ];")?;
    writeln!(f)?;

    emit_str_accessor(&mut f, "as_str", "The RPC's wire name.", &rpcs, |r| &r.name)?;
    emit_str_accessor(
        &mut f,
        "request_type",
        "Fully-qualified request message type.",
        &rpcs,
        |r| &r.request,
    )?;
    emit_str_accessor(
        &mut f,
        "response_type",
        "Fully-qualified response message type.",
        &rpcs,
        |r| &r.response,
    )?;

    writeln!(f, "    /// `true` when the response is a server stream.")?;
    writeln!(f, "    #[must_use]")?;
    writeln!(f, "    pub const fn server_streaming(self) -> bool {{")?;
    writeln!(f, "        match self {{")?;
    for r in &rpcs {
        writeln!(
            f,
            "            GatewayRpc::{} => {},",
            r.name, r.server_streaming
        )?;
    }
    writeln!(f, "        }}")?;
    writeln!(f, "    }}")?;
    writeln!(f, "}}")?;

    f.flush()?;
    Ok(())
}

fn emit_str_accessor<W: Write, F>(
    f: &mut W,
    fn_name: &str,
    doc: &str,
    rpcs: &[Rpc],
    field: F,
) -> std::io::Result<()>
where
    F: Fn(&Rpc) -> &String,
{
    writeln!(f, "    /// {doc}")?;
    writeln!(f, "    #[must_use]")?;
    writeln!(f, "    pub const fn {fn_name}(self) -> &'static str {{")?;
    writeln!(f, "        match self {{")?;
    for r in rpcs {
        writeln!(
            f,
            "            GatewayRpc::{} => {:?},",
            r.name,
            field(r).as_str()
        )?;
    }
    writeln!(f, "        }}")?;
    writeln!(f, "    }}")?;
    writeln!(f)?;
    Ok(())
}

fn strip_leading_dot(s: &str) -> String {
    s.strip_prefix('.').unwrap_or(s).to_string()
}
