//! Four backend impl/stubs behind the `MoteExecutor` trait (D31 + D41).
//!
//! - [`bwrap::BwrapExecutor`] — Linux real impl (skeleton at PR 9a; real
//!   bubblewrap spawn lands in the PR 9a-hardening follow-up).
//! - [`macos_sandbox::MacOsSandboxExecutor`] — macOS real impl (skeleton at
//!   PR 9a; real `posix_spawn` + `sandbox_init`-equivalent lands in the
//!   PR 9a-hardening follow-up). Per D46 the SBPL profile is generated by
//!   `profile_from_warrant`.
//! - [`oci_daemon::OciDaemonExecutor`] — warrant-declared opt-in stub (full
//!   impl deferred per D31 PENDING EXTERNAL VERIFICATION).
//! - [`cloud_microvm::CloudMicroVmExecutor`] — refusal on every platform in
//!   OSS; concrete impl lives behind the cloud feature flag per D28.

pub mod bwrap;
pub mod cloud_microvm;
pub mod macos_sandbox;
pub mod oci_daemon;
