# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kortecx.v1 import gateway_pb2 as kortecx_dot_v1_dot_gateway__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in kortecx/v1/gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KxGatewayStub(object):
    """---------------------------------------------------------------------------
    Service — the external client-facing gateway (distinct from Coordinator).
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitRun = channel.unary_unary(
                '/kortecx.v1.KxGateway/SubmitRun',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.SubmitRunRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.RunHandle.FromString,
                _registered_method=True)
        self.Invoke = channel.unary_unary(
                '/kortecx.v1.KxGateway/Invoke',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.InvokeRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.InvokeResponse.FromString,
                _registered_method=True)
        self.GetProjection = channel.unary_unary(
                '/kortecx.v1.KxGateway/GetProjection',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.GetProjectionRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.ProjectionView.FromString,
                _registered_method=True)
        self.GetContent = channel.unary_unary(
                '/kortecx.v1.KxGateway/GetContent',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.GetContentRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.ContentBlob.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/kortecx.v1.KxGateway/StreamEvents',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.EventFrame.FromString,
                _registered_method=True)
        self.ListSignatures = channel.unary_unary(
                '/kortecx.v1.KxGateway/ListSignatures',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.ListSignaturesRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListSignaturesResponse.FromString,
                _registered_method=True)
        self.GetSignature = channel.unary_unary(
                '/kortecx.v1.KxGateway/GetSignature',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.GetSignatureRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.GetSignatureResponse.FromString,
                _registered_method=True)
        self.RegisterSignature = channel.unary_unary(
                '/kortecx.v1.KxGateway/RegisterSignature',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.RegisterSignatureRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.RegisterSignatureResponse.FromString,
                _registered_method=True)
        self.ListRuns = channel.unary_unary(
                '/kortecx.v1.KxGateway/ListRuns',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.ListRunsRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListRunsResponse.FromString,
                _registered_method=True)
        self.ListRecipes = channel.unary_unary(
                '/kortecx.v1.KxGateway/ListRecipes',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.ListRecipesRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListRecipesResponse.FromString,
                _registered_method=True)
        self.GetRecipeForm = channel.unary_unary(
                '/kortecx.v1.KxGateway/GetRecipeForm',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.GetRecipeFormRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.GetRecipeFormResponse.FromString,
                _registered_method=True)
        self.ListTeams = channel.unary_unary(
                '/kortecx.v1.KxGateway/ListTeams',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.ListTeamsRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListTeamsResponse.FromString,
                _registered_method=True)
        self.ListTeamMembers = channel.unary_unary(
                '/kortecx.v1.KxGateway/ListTeamMembers',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.ListTeamMembersRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListTeamMembersResponse.FromString,
                _registered_method=True)
        self.ListAssetGrants = channel.unary_unary(
                '/kortecx.v1.KxGateway/ListAssetGrants',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.ListAssetGrantsRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListAssetGrantsResponse.FromString,
                _registered_method=True)
        self.ListDatasets = channel.unary_unary(
                '/kortecx.v1.KxGateway/ListDatasets',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.ListDatasetsRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListDatasetsResponse.FromString,
                _registered_method=True)
        self.IngestDocuments = channel.unary_unary(
                '/kortecx.v1.KxGateway/IngestDocuments',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.IngestDocumentsRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.IngestDocumentsResponse.FromString,
                _registered_method=True)
        self.QueryDataset = channel.unary_unary(
                '/kortecx.v1.KxGateway/QueryDataset',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.QueryDatasetRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.QueryDatasetResponse.FromString,
                _registered_method=True)
        self.ListReplanRounds = channel.unary_unary(
                '/kortecx.v1.KxGateway/ListReplanRounds',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.ListReplanRoundsRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListReplanRoundsResponse.FromString,
                _registered_method=True)
        self.ListReactTurns = channel.unary_unary(
                '/kortecx.v1.KxGateway/ListReactTurns',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.ListReactTurnsRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListReactTurnsResponse.FromString,
                _registered_method=True)
        self.ListCaptureRecords = channel.unary_unary(
                '/kortecx.v1.KxGateway/ListCaptureRecords',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.ListCaptureRecordsRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListCaptureRecordsResponse.FromString,
                _registered_method=True)
        self.ListToolManifests = channel.unary_unary(
                '/kortecx.v1.KxGateway/ListToolManifests',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.ListToolManifestsRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListToolManifestsResponse.FromString,
                _registered_method=True)
        self.ScoreTaskBundle = channel.unary_unary(
                '/kortecx.v1.KxGateway/ScoreTaskBundle',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.ScoreTaskBundleRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.ScoreTaskBundleResponse.FromString,
                _registered_method=True)


class KxGatewayServicer(object):
    """---------------------------------------------------------------------------
    Service — the external client-facing gateway (distinct from Coordinator).
    ---------------------------------------------------------------------------

    """

    def SubmitRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Invoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSignatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSignature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterSignature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuns(self, request, context):
        """UI-2 additive (D120.6): run enumeration + recipe discovery.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRecipes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecipeForm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTeams(self, request, context):
        """UI-3 additive (D120.6): teams (membership) + sharing (grants) read viewers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTeamMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAssetGrants(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDatasets(self, request, context):
        """T3.7 additive (D120.6): the Datasets data-plane (RAG).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReplanRounds(self, request, context):
        """PR-2c-2 additive (D120.6): re-plan-round observability (read-only).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReactTurns(self, request, context):
        """PR-2d-1 additive (D120.6): ReAct-turn observability (read-only).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCaptureRecords(self, request, context):
        """Campaign Batch 2 additive (D120.6): the Morphic Data Engine capture read
        surface (durable action exhaust; read-only, off-truth-path).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListToolManifests(self, request, context):
        """W1.A5 toolscout additive (D120.6): advisory tool discovery + TaskBundle
        preview (read-only, display-only — scores/verdicts never authorize).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScoreTaskBundle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KxGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitRun': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitRun,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.SubmitRunRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.RunHandle.SerializeToString,
            ),
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.InvokeRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.InvokeResponse.SerializeToString,
            ),
            'GetProjection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjection,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.GetProjectionRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.ProjectionView.SerializeToString,
            ),
            'GetContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContent,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.GetContentRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.ContentBlob.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.StreamEventsRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.EventFrame.SerializeToString,
            ),
            'ListSignatures': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSignatures,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListSignaturesRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.ListSignaturesResponse.SerializeToString,
            ),
            'GetSignature': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSignature,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.GetSignatureRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.GetSignatureResponse.SerializeToString,
            ),
            'RegisterSignature': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSignature,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.RegisterSignatureRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.RegisterSignatureResponse.SerializeToString,
            ),
            'ListRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuns,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListRunsRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.ListRunsResponse.SerializeToString,
            ),
            'ListRecipes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRecipes,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListRecipesRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.ListRecipesResponse.SerializeToString,
            ),
            'GetRecipeForm': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecipeForm,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.GetRecipeFormRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.GetRecipeFormResponse.SerializeToString,
            ),
            'ListTeams': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTeams,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListTeamsRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.ListTeamsResponse.SerializeToString,
            ),
            'ListTeamMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTeamMembers,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListTeamMembersRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.ListTeamMembersResponse.SerializeToString,
            ),
            'ListAssetGrants': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAssetGrants,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListAssetGrantsRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.ListAssetGrantsResponse.SerializeToString,
            ),
            'ListDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDatasets,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListDatasetsRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.ListDatasetsResponse.SerializeToString,
            ),
            'IngestDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestDocuments,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.IngestDocumentsRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.IngestDocumentsResponse.SerializeToString,
            ),
            'QueryDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryDataset,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.QueryDatasetRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.QueryDatasetResponse.SerializeToString,
            ),
            'ListReplanRounds': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReplanRounds,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListReplanRoundsRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.ListReplanRoundsResponse.SerializeToString,
            ),
            'ListReactTurns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReactTurns,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListReactTurnsRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.ListReactTurnsResponse.SerializeToString,
            ),
            'ListCaptureRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCaptureRecords,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListCaptureRecordsRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.ListCaptureRecordsResponse.SerializeToString,
            ),
            'ListToolManifests': grpc.unary_unary_rpc_method_handler(
                    servicer.ListToolManifests,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListToolManifestsRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.ListToolManifestsResponse.SerializeToString,
            ),
            'ScoreTaskBundle': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreTaskBundle,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.ScoreTaskBundleRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.ScoreTaskBundleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kortecx.v1.KxGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kortecx.v1.KxGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KxGateway(object):
    """---------------------------------------------------------------------------
    Service — the external client-facing gateway (distinct from Coordinator).
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def SubmitRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/SubmitRun',
            kortecx_dot_v1_dot_gateway__pb2.SubmitRunRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.RunHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/Invoke',
            kortecx_dot_v1_dot_gateway__pb2.InvokeRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.InvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProjection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/GetProjection',
            kortecx_dot_v1_dot_gateway__pb2.GetProjectionRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.ProjectionView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/GetContent',
            kortecx_dot_v1_dot_gateway__pb2.GetContentRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.ContentBlob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kortecx.v1.KxGateway/StreamEvents',
            kortecx_dot_v1_dot_gateway__pb2.StreamEventsRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.EventFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSignatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/ListSignatures',
            kortecx_dot_v1_dot_gateway__pb2.ListSignaturesRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.ListSignaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSignature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/GetSignature',
            kortecx_dot_v1_dot_gateway__pb2.GetSignatureRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.GetSignatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterSignature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/RegisterSignature',
            kortecx_dot_v1_dot_gateway__pb2.RegisterSignatureRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.RegisterSignatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/ListRuns',
            kortecx_dot_v1_dot_gateway__pb2.ListRunsRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.ListRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRecipes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/ListRecipes',
            kortecx_dot_v1_dot_gateway__pb2.ListRecipesRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.ListRecipesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecipeForm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/GetRecipeForm',
            kortecx_dot_v1_dot_gateway__pb2.GetRecipeFormRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.GetRecipeFormResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTeams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/ListTeams',
            kortecx_dot_v1_dot_gateway__pb2.ListTeamsRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.ListTeamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTeamMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/ListTeamMembers',
            kortecx_dot_v1_dot_gateway__pb2.ListTeamMembersRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.ListTeamMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAssetGrants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/ListAssetGrants',
            kortecx_dot_v1_dot_gateway__pb2.ListAssetGrantsRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.ListAssetGrantsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/ListDatasets',
            kortecx_dot_v1_dot_gateway__pb2.ListDatasetsRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.ListDatasetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/IngestDocuments',
            kortecx_dot_v1_dot_gateway__pb2.IngestDocumentsRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.IngestDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/QueryDataset',
            kortecx_dot_v1_dot_gateway__pb2.QueryDatasetRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.QueryDatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReplanRounds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/ListReplanRounds',
            kortecx_dot_v1_dot_gateway__pb2.ListReplanRoundsRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.ListReplanRoundsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReactTurns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/ListReactTurns',
            kortecx_dot_v1_dot_gateway__pb2.ListReactTurnsRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.ListReactTurnsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCaptureRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/ListCaptureRecords',
            kortecx_dot_v1_dot_gateway__pb2.ListCaptureRecordsRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.ListCaptureRecordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListToolManifests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/ListToolManifests',
            kortecx_dot_v1_dot_gateway__pb2.ListToolManifestsRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.ListToolManifestsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScoreTaskBundle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/ScoreTaskBundle',
            kortecx_dot_v1_dot_gateway__pb2.ScoreTaskBundleRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.ScoreTaskBundleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
