# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kortecx.v1 import gateway_pb2 as kortecx_dot_v1_dot_gateway__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in kortecx/v1/gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KxGatewayStub(object):
    """---------------------------------------------------------------------------
    Service — the external client-facing gateway (distinct from Coordinator).
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitRun = channel.unary_unary(
                '/kortecx.v1.KxGateway/SubmitRun',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.SubmitRunRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.RunHandle.FromString,
                _registered_method=True)
        self.Invoke = channel.unary_unary(
                '/kortecx.v1.KxGateway/Invoke',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.InvokeRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.InvokeResponse.FromString,
                _registered_method=True)
        self.GetProjection = channel.unary_unary(
                '/kortecx.v1.KxGateway/GetProjection',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.GetProjectionRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.ProjectionView.FromString,
                _registered_method=True)
        self.GetContent = channel.unary_unary(
                '/kortecx.v1.KxGateway/GetContent',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.GetContentRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.ContentBlob.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/kortecx.v1.KxGateway/StreamEvents',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.EventFrame.FromString,
                _registered_method=True)
        self.ListSignatures = channel.unary_unary(
                '/kortecx.v1.KxGateway/ListSignatures',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.ListSignaturesRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListSignaturesResponse.FromString,
                _registered_method=True)
        self.GetSignature = channel.unary_unary(
                '/kortecx.v1.KxGateway/GetSignature',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.GetSignatureRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.GetSignatureResponse.FromString,
                _registered_method=True)
        self.RegisterSignature = channel.unary_unary(
                '/kortecx.v1.KxGateway/RegisterSignature',
                request_serializer=kortecx_dot_v1_dot_gateway__pb2.RegisterSignatureRequest.SerializeToString,
                response_deserializer=kortecx_dot_v1_dot_gateway__pb2.RegisterSignatureResponse.FromString,
                _registered_method=True)


class KxGatewayServicer(object):
    """---------------------------------------------------------------------------
    Service — the external client-facing gateway (distinct from Coordinator).
    ---------------------------------------------------------------------------

    """

    def SubmitRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Invoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSignatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSignature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterSignature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KxGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitRun': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitRun,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.SubmitRunRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.RunHandle.SerializeToString,
            ),
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.InvokeRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.InvokeResponse.SerializeToString,
            ),
            'GetProjection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjection,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.GetProjectionRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.ProjectionView.SerializeToString,
            ),
            'GetContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContent,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.GetContentRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.ContentBlob.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.StreamEventsRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.EventFrame.SerializeToString,
            ),
            'ListSignatures': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSignatures,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.ListSignaturesRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.ListSignaturesResponse.SerializeToString,
            ),
            'GetSignature': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSignature,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.GetSignatureRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.GetSignatureResponse.SerializeToString,
            ),
            'RegisterSignature': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSignature,
                    request_deserializer=kortecx_dot_v1_dot_gateway__pb2.RegisterSignatureRequest.FromString,
                    response_serializer=kortecx_dot_v1_dot_gateway__pb2.RegisterSignatureResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kortecx.v1.KxGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kortecx.v1.KxGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KxGateway(object):
    """---------------------------------------------------------------------------
    Service — the external client-facing gateway (distinct from Coordinator).
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def SubmitRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/SubmitRun',
            kortecx_dot_v1_dot_gateway__pb2.SubmitRunRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.RunHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/Invoke',
            kortecx_dot_v1_dot_gateway__pb2.InvokeRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.InvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProjection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/GetProjection',
            kortecx_dot_v1_dot_gateway__pb2.GetProjectionRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.ProjectionView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/GetContent',
            kortecx_dot_v1_dot_gateway__pb2.GetContentRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.ContentBlob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kortecx.v1.KxGateway/StreamEvents',
            kortecx_dot_v1_dot_gateway__pb2.StreamEventsRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.EventFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSignatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/ListSignatures',
            kortecx_dot_v1_dot_gateway__pb2.ListSignaturesRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.ListSignaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSignature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/GetSignature',
            kortecx_dot_v1_dot_gateway__pb2.GetSignatureRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.GetSignatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterSignature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kortecx.v1.KxGateway/RegisterSignature',
            kortecx_dot_v1_dot_gateway__pb2.RegisterSignatureRequest.SerializeToString,
            kortecx_dot_v1_dot_gateway__pb2.RegisterSignatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
