//! D139: compile-time embed of the web console (`console` feature ONLY).
//!
//! When the `console` feature is enabled this script walks the built SPA
//! (`ui/dist` by default; `KX_CONSOLE_DIST` overrides) and generates
//! `console_assets.rs` — a static manifest of `include_bytes!` entries with a
//! content type and an immutable-cache flag per file. The gateway then serves
//! ONLY these embedded bytes: there is no runtime file serving, so path
//! traversal is structurally impossible and the binary is self-contained.
//!
//! Without the feature the script is a no-op, so plain `cargo build/install`
//! (and `check-reproducible`'s default-features workspace build) never needs
//! node or a built dist. A console build with a missing dist fails LOUDLY with
//! the remedy, never silently embeds an empty console.

// Build-script allows (the workspace-lints comment sanctions these here):
// panic-on-missing IS the correct build-script behavior (a broken embed must
// fail the build loudly), and the `{:?}` writes are deliberate — Debug quoting
// IS the string-literal escaping for the generated Rust source.
#![allow(
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::map_unwrap_or,
    clippy::unnecessary_debug_formatting
)]

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // Re-run when the feature set or the dist location changes.
    println!("cargo:rerun-if-env-changed=KX_CONSOLE_DIST");

    if env::var_os("CARGO_FEATURE_CONSOLE").is_none() {
        return; // default build: no embed, no node, byte-identical.
    }

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let dist = env::var_os("KX_CONSOLE_DIST")
        .map(PathBuf::from)
        .unwrap_or_else(|| manifest_dir.join("../../ui/dist"));
    println!("cargo:rerun-if-changed={}", dist.display());

    assert!(
        dist.join("index.html").is_file(),
        "the `console` feature embeds the built web console, but {} has no index.html.\n\
         Build it first:\n\
         \tnpm --prefix bindings/typescript ci && npm --prefix bindings/typescript run build\n\
         \tnpm --prefix ui ci && npm --prefix ui run build\n\
         (or `just console-dist`), set KX_CONSOLE_DIST to a built dist, use the prebuilt\n\
         release binary, or build without `--features console`.",
        dist.display()
    );

    let mut files = Vec::new();
    collect(&dist, &dist, &mut files);
    // Deterministic manifest order regardless of filesystem iteration order.
    files.sort();

    // Re-run when any embedded FILE changes, not just the directory: a directory
    // mtime does not reliably move when files inside are rewritten in place, so a
    // rebuilt `ui/dist` could otherwise ship a SILENTLY STALE embedded console
    // (observed 2026-06-12: a fresh dist + `cargo build` kept serving the old
    // bundle until a forced `cargo clean -p kx-gateway`). The directory line above
    // still catches added/removed files; these per-file lines catch content swaps.
    for rel in &files {
        println!("cargo:rerun-if-changed={}", dist.join(rel).display());
    }

    let mut out = String::new();
    out.push_str(
        "/// One embedded console file (generated by build.rs — see the crate's build script).\n\
         pub(crate) struct Asset {\n\
         \t/// The URL path relative to the console root (no leading slash).\n\
         \tpub(crate) path: &'static str,\n\
         \t/// The file bytes, embedded at compile time.\n\
         \tpub(crate) bytes: &'static [u8],\n\
         \t/// The response Content-Type.\n\
         \tpub(crate) content_type: &'static str,\n\
         \t/// `true` for hash-named files safe to cache forever (`assets/*`).\n\
         \tpub(crate) immutable: bool,\n\
         }\n\n\
         /// Every embedded console file, sorted by path.\n\
         pub(crate) static ASSETS: &[Asset] = &[\n",
    );
    for rel in &files {
        let abs = dist.join(rel);
        let mime = mime_for(rel);
        let immutable = rel.starts_with("assets/");
        let _ = writeln!(
            out,
            "\tAsset {{ path: {rel:?}, bytes: include_bytes!({abs:?}), \
             content_type: {mime:?}, immutable: {immutable} }},",
            abs = abs.canonicalize().expect("dist file path canonicalizes"),
        );
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("console_assets.rs"), out).expect("write console_assets.rs");
}

/// Recursively collect files under `dir` as `/`-separated paths relative to `root`.
fn collect(root: &Path, dir: &Path, out: &mut Vec<String>) {
    for entry in fs::read_dir(dir).expect("read dist dir") {
        let entry = entry.expect("read dist entry");
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
        } else {
            let rel = path
                .strip_prefix(root)
                .expect("dist file under root")
                .components()
                .map(|c| c.as_os_str().to_string_lossy())
                .collect::<Vec<_>>()
                .join("/");
            out.push(rel);
        }
    }
}

/// Content-Type by extension — the small closed set a Vite dist emits. Anything
/// else is served as opaque bytes (never sniffed; the gateway sends nosniff).
fn mime_for(path: &str) -> &'static str {
    match path.rsplit_once('.').map(|(_, ext)| ext) {
        Some("html") => "text/html; charset=utf-8",
        Some("js" | "mjs") => "application/javascript",
        Some("css") => "text/css",
        Some("json" | "map") => "application/json",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("ico") => "image/x-icon",
        Some("woff") => "font/woff",
        Some("woff2") => "font/woff2",
        Some("txt") => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    }
}
